package com.softwaremagico.ktg.gui.tournament;
/*
 * #%L
 * KendoTournamentGenerator
 * %%
 * Copyright (C) 2008 - 2012 Softwaremagico
 * %%
 * This software is designed by Jorge Hortelano Otero. Jorge Hortelano Otero
 * <softwaremagico@gmail.com> Valencia (Spain).
 *  
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *  
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *  
 * You should have received a copy of the GNU General Public License along with
 * this program; If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import com.softwaremagico.ktg.core.Tournament;
import com.softwaremagico.ktg.tournament.TournamentType;
import com.softwaremagico.ktg.tournament.TournamentManagerFactory;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JScrollBar;
import javax.swing.Timer;

public class TournamentEvolution extends javax.swing.JFrame {

    BlackBoardPanel bbp;
    Timer timer = null;
    final int seconds = 5;
    int center = 21;
    private Tournament tournament;

    /**
     * Creates new form TournamentEvolution
     */
    public TournamentEvolution(Tournament tournament) {
        this.tournament = tournament;
        initComponents();
        setLocation((int) Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2 - (int) (this.getWidth() / 2),
                (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2 - (int) (this.getHeight() / 2));
        this.setSize(new Dimension((int) Toolkit.getDefaultToolkit().getScreenSize().getWidth(), (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight()));
        this.setExtendedState(this.getExtendedState() | TournamentEvolution.MAXIMIZED_BOTH);
        bbp = new BlackBoardPanel(null, false);
        BlackBoardScrollPane.setViewportView(bbp);
    }

    public void updateBlackBoard(Tournament tournament, boolean refill) {
        this.tournament = tournament;
        if (!tournament.getType().equals(TournamentType.SIMPLE)) {
            bbp.update(tournament);
            BlackBoardScrollPane.revalidate();
            BlackBoardScrollPane.repaint();
            if (timer == null) {
                startTimer(tournament);
            }
        } else {
            this.dispose();
        }
    }

    private void startTimer(final Tournament tournament) {
        timer = new Timer(seconds * 100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                updateBlackBoard(tournament, true);
                centerImage();
            }
        });
        timer.setRepeats(true);
        timer.start();
    }

    private void centerImage() {
        JScrollBar verticalScrollBar = BlackBoardScrollPane.getVerticalScrollBar();
        JScrollBar horizontalScrollBar = BlackBoardScrollPane.getHorizontalScrollBar();
        int columns = 1;
        int rows = 1;
        try {
            columns = horizontalScrollBar.getMaximum() / TournamentManagerFactory.getManager(tournament).getNumberOfLevels();
            rows = verticalScrollBar.getMaximum() / TournamentManagerFactory.getManager(tournament).getGroups(0).size();
        } catch (ArithmeticException ae) {
        }

        Integer x = TournamentManagerFactory.getManager(tournament).getLastLevelUsed();

        if (x == null) {
            x = TournamentManagerFactory.getManager(tournament).getNumberOfLevels() - 1;
        }

        int y;

        if (tournament.getHowManyTeamsOfGroupPassToTheTree() < 2) {
            y = (int) (Math.pow(2, x + 1));
        } else {
            if (x == 0) {
                y = (int) (Math.pow(2, x + 1));
            } else {
                y = (int) (Math.pow(2, x));
            }
        }

        verticalScrollBar.setValue(rows * y);
        horizontalScrollBar.setValue(columns * x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BlackBoardScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("League Viewer");
        setAlwaysOnTop(true);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BlackBoardScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BlackBoardScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        int ke = evt.getKeyCode();

        // ESC or q pressed (with bloq num and without)
        if ((ke == 1048689) || (ke == 1048603) || (ke == 27) || (ke == 113)) {
            timer.stop();
            timer = null;
            this.dispose();
        }
    }//GEN-LAST:event_formKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JScrollPane BlackBoardScrollPane;
    // End of variables declaration//GEN-END:variables
}
