package com.softwaremagico.ktg.lists;

/*
 * #%L
 * KendoTournamentGenerator
 * %%
 * Copyright (C) 2008 - 2012 Softwaremagico
 * %%
 * This software is designed by Jorge Hortelano Otero.
 * Jorge Hortelano Otero <softwaremagico@gmail.com>
 * C/Quart 89, 3. Valencia CP:46008 (Spain).
 *  
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program; If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import com.softwaremagico.ktg.core.Team;
import com.softwaremagico.ktg.persistence.TeamPool;
import com.softwaremagico.ktg.gui.AlertManager;
import com.softwaremagico.ktg.gui.base.KendoFrame;
import com.softwaremagico.ktg.language.LanguagePool;
import com.softwaremagico.ktg.language.Translator;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public abstract class ListFromTeams extends KendoFrame {

	public Translator trans = null;
	public List<Team> listTeams = new ArrayList<>();
	private boolean voidTournament;

	public void Start(boolean tmp_voidTournament) {
		initComponents();
		setLocation((int) Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 2 - (int) (this.getWidth() / 2),
				(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 2 - (int) (this.getHeight() / 2));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setLanguage();
		voidTournament = tmp_voidTournament;
		fillTeams();
		CheckBox.setVisible(false);
	}

	public void setLanguage() {
		trans = LanguagePool.getTranslator("gui.xml");
		TeamLabel.setText(trans.getTranslatedText("TeamLabel"));
		CancelButton.setText(trans.getTranslatedText("CancelButton"));
		GenerateButton.setText(trans.getTranslatedText("GenerateButton"));
	}

	private void fillTeams() {
		try {
			listTeams = TeamPool.getInstance().getAll();
			if (voidTournament) {
				TeamComboBox.addItem(trans.getTranslatedText("All"));
			}
			for (int i = 0; i < listTeams.size(); i++) {
				TeamComboBox.addItem(listTeams.get(i).getName() + " (" + listTeams.get(i).getTournament().getName()
						+ ")");
			}
			if (TeamComboBox.getItemCount() > 0) {
				TeamComboBox.setSelectedIndex(0);
			}
		} catch (NullPointerException npe) {
		} catch (SQLException ex) {
			AlertManager.showSqlErrorMessage(ex);
		}
	}

	public Team returnSelectedTeam() {
		if (voidTournament && TeamComboBox.getSelectedIndex() <= 0) {
			return null;
		}
		return listTeams.get(TeamComboBox.getSelectedIndex() - 1);
	}

	public abstract void Generate();

	public void CkeckBoxClicked() {
	}

	/**
	 * **********************************************
	 * 
	 * LISTENERS
	 * 
	 *********************************************** 
	 */
	/**
	 * Add the same action listener to all langugaes of the menu.
	 * 
	 * @param al
	 */
	public void addGenerateButtonListener(ActionListener al) {
		GenerateButton.addActionListener(al);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeamComboBox = new javax.swing.JComboBox();
        TeamLabel = new javax.swing.JLabel();
        GenerateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TeamLabel.setText("Team:");

        GenerateButton.setText("Generate List");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CheckBox.setText("CheckBox");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox)
                    .addComponent(TeamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton))
                    .addComponent(TeamComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CancelButton, GenerateButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(GenerateButton)
                    .addComponent(CheckBox))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GenerateButtonActionPerformed
		Generate();
	}// GEN-LAST:event_GenerateButtonActionPerformed

	private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CancelButtonActionPerformed
		this.dispose();
	}// GEN-LAST:event_CancelButtonActionPerformed

	private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CheckBoxActionPerformed
		CkeckBoxClicked();
	}// GEN-LAST:event_CheckBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    public javax.swing.JCheckBox CheckBox;
    protected javax.swing.JButton GenerateButton;
    protected javax.swing.JComboBox TeamComboBox;
    private javax.swing.JLabel TeamLabel;
    // End of variables declaration//GEN-END:variables
}
